#!/bin/bash

set -x

DST_USER=$1

# constants
ROOT_DIR=/jupyter
USER_DIR=$ROOT_DIR/users/$DST_USER
SRC_COPYBOOK=$ROOT_DIR/admin/copybook
SRC_INFO=$ROOT_DIR/admin/info
SRC_TOOLS=$ROOT_DIR/admin/tools

usage()
{
  cat <<EOF

Usage:
  ${0##*/} USER_NAME

  Arguments:
    USER_NAME : user name of the distribution.
EOF
  exit 1
}

# check arguments
[ "$#" -eq 1 ] || {
  usage
}

# get user entry
user_entry=$(ls -l "$ROOT_DIR/users" | egrep " $DST_USER$")
# check user entry
[ -z "$user_entry" ] && {
  echo "user '$DST_USER' does not exist"
  usage
}
# get user id
user_id=$(echo $user_entry | awk '{print $3}')
# get group id
group_id=$(echo $user_entry | awk '{print $4}')

# distribution
sudo -u \#$user_id -g \#$group_id rsync -rltvuO --delete --include='*.ipynb' --exclude='*' $SRC_COPYBOOK/ $USER_DIR
