#!/bin/bash

DST_USER=$1

usage()
{
  cat <<EOF

Usage:
  ${0##*/} USER_NAME

  Arguments:
    USER_NAME : user name of the distribution.
EOF
  exit 1
}


[ "$#" -eq 1 ] || {
  usage
}
 
# check user
[ $(cat /etc/passwd | grep $DST_USER) ] || {
  echo "user '$DST_USER' does not exist"
  usage
}


ROOT_DIR=/jupyter
SRC_NOTEBOOK=$ROOT_DIR/admin/copybook
DST_NOTEBOOK=$ROOT_DIR/users/$DST_USER

sudo -u $DST_USER rsync -rvutl --delete --include='*.ipynb' --exclude='*' $SRC_NOTEBOOK/ $DST_NOTEBOOK
