#!/bin/bash
source ~/.auth-proxy
ssh -i ~/.ssh/ssh-auth-proxy -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -q ubuntu@${AUTH_PROXY_IP} -q "sudo docker exec -i ${AUTH_PROXY_NAME} bash"
